# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/ChessServer.csproj'
  displayName: 'Run a multi-line script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/ServerTests.csproj'
    testRunTitle: 'MainTests'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'